### PR TITLE
Add a changelog

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR adds a [changelog](https://keepachangelog.com/en/1.0.0/) to keep track of changes within the Node SDK.

The changelog has been backfilled with the release notes from each version.

### CODE REVIEW

**Review by zlwaterfield — APPROVED** [review]
Is this auto-generated or is this done manually for each release?

**Comment by maxdeviant** [comment]
> Is this auto-generated or is this done manually for each release?

It's currently manual.

The idea is that while changes are made they get added to the `Unreleased` section and then when we cut a release we just rename `Unreleased` to the new version.

**Review by marktran — CHANGES_REQUESTED** [review]
What's the advantage of a `CHANGELOG` file vs GitHub Releases? What's the process for updating it and making releases?

If we add it to this SDK, it should also be added to all the other SDKs for consistency.

**Comment by maxdeviant** [comment]
> What's the advantage of a `CHANGELOG` file vs GitHub Releases?

The main advantage of having a `CHANGELOG` is that you can have a draft state of all unreleased changes. So every time a change is made, you can add an entry under `Unreleased`. Then when you cut a release, you don't need to go back and try to remember all of the changes that are going into the release.

Additionally, the `CHANGELOG` in the repo is versioned with the project, and is more easily accessible to library consumers, especially if they want to view the changes since some very old version (as they don't have to dig through pages of GitHub releases).

The two are not mutually exclusive, and what projects will typically do is create a GitHub Release and take the contents of the changelog for that version and copy-paste it into the GitHub Release description.

Here's what the Keep a Changelog site says on the matter:

> It's a great initiative. Releases can be used to turn simple git tags (for example a tag named v1.0.0) into rich release notes by manually adding release notes or it can pull annotated git tag messages and turn them into notes.
> 
> GitHub Releases create a non-portable changelog that can only be displayed to users within the context of GitHub. It's possible to make them look very much like the Keep a Changelog format, but it tends to be a bit more involved.
>
> The current version of GitHub releases is also arguably not very discoverable by end-users, unlike the typical uppercase files (README, CONTRIBUTING, etc.). Another minor issue is that the interface doesn't currently offer links to commit logs between each release.

---

> What's the process for updating it and making releases?

Each time a change is made it is added under the `Unreleased` section in `CHANGELOG.md` under the corresponding section. Keep a Changelog defines the following sections:

- `Added` for new features.
- `Changed` for changes in existing functionality.
- `Deprecated` for soon-to-be removed features.
- `Removed` for now removed features.
- `Fixed` for any bug fixes.
- `Security` in case of vulnerabilities.

For example, a PR that fixes a bug would add a line about the fix under `Fixed`.

When making a release you would change `Unreleased` to the version being released, add a date, update the links at bottom of the changelog, and add a new, empty `Unreleased` section at the top. If the changes were kept on top of as they were made then the maintainer cutting the release shouldn't need to make any changes to the content of the changelog for that release.

> If we add it to this SDK, it should also be added to all the other SDKs for consistency.

I agree that we would want to adopt this across the board.

**Comment by maxdeviant** [comment]
Closing this out until we decide to revisit.

**Pull request closed without merging**
